eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
    hostname: localhost

server:
  port: 9802
spring:
  application:
    name: ORDER-PROVIDER
